<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="Admin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    
    <link rel="stylesheet" href="StyleSheet.css" type="text/css" runat="server"/>
    <style>
        .header
{
background-color: #646464;
font-family: Arial;
color: White;
border: none 0px transparent;
height: 25px;
text-align: center;
font-size: 16px;
}

.rows
{
background-color: #808080;
font-family: Arial;
font-size: 14px;
color: #000;
min-height: 25px;
text-align: left;
border: none 0px transparent;
}
.rows:hover
{
background-color: #000000;
font-family: Arial;
color: #fff;
text-align: left;
}
.selectedrow
{
background-color: #ff8000;
font-family: Arial;
color: #fff;
font-weight: bold;
text-align: left;
}
.GridView1
{
    color: black;
    width: 100%;
}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table width="60%" align="center">
        <tr>
            <th align="left"><h2>Welcome to Admin View</h2></th>
        </tr>
        <tr>
            <td align="left">
                <h2>Add New Product</h2>
            </td>
        </tr>
        <tr>
            <td>
                <table>
                    <tr>
                        <td>Model </td>
                        <td>
                        <asp:TextBox ID="txtModel" runat="server"></asp:TextBox> </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="txtModel" ErrorMessage="*Input model" Font-Bold="True" ForeColor="Red"></asp:RequiredFieldValidator>
        
                        </td>
                    </tr>
                    <tr>
                        <td>Company </td>
                        <td>
                        <asp:TextBox ID="txtCompany" runat="server"></asp:TextBox> </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtCompany" ErrorMessage="*Input company" Font-Bold="True" ForeColor="Red"></asp:RequiredFieldValidator>
        
                        </td>
                    </tr>
                    <tr>
                        <td>Price </td>
                        <td>
                        <asp:TextBox ID="txtPrice" runat="server" TextMode="Number"></asp:TextBox> </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="txtPrice" ErrorMessage="*Input price" Font-Bold="True" ForeColor="Red"></asp:RequiredFieldValidator>
        
                        </td>
                    </tr>
                    <tr>
                        <td>Available items </td>
                        <td>
                        <asp:TextBox ID="txtItems" runat="server" TextMode="Number"></asp:TextBox> </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="txtItems" ErrorMessage="*Input available items" Font-Bold="True" ForeColor="Red"></asp:RequiredFieldValidator>
        
                        </td>
                    </tr>

                    <tr>
                        <td colspan="3">
                            <asp:Button ID="btnAdd" runat="server" Text="Add Product" OnClick="btnAdd_Click" />

                        </td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <asp:Label ID="Label1" runat="server" Text=""></asp:Label>

                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td align="left">
                <h2>View , Update or Delete Product</h2>
            </td>
        </tr>
        <tr>
            <td>
                <asp:GridView ID="GridView1" runat="server" DataKeyNames="laptopId" CssClass="mydatagrid" PagerStyle-CssClass="pager"
 HeaderStyle-CssClass="header" RowStyle-CssClass="rows" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
</asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

